"""
Cross-check invariants computed in this repo against the GAP package
`numericalsgps`. Implements falsification rule 8 (vary the measurement method).

This script does TWO things:
    1. From a JSON file (n1_results or kunz_fast output), build a GAP script
       that recomputes (m, e, F, c, g, t, L, W) for each semigroup via its
       minimal generators, then dumps the results as a JSON-like file.
    2. Parse GAP's output and report any mismatch.

If GAP is not installed, step 1 only writes the script to disk and exits
with instructions; the user runs it manually on a machine with GAP.

Usage:
    # Generate the GAP script from a sample of 500 semigroups
    python gap_cross_check.py --input ../data/n1_results_g20.json \\
                              --sample 500 --gap-script /tmp/check.g

    # After running `gap /tmp/check.g > /tmp/check.out` manually:
    python gap_cross_check.py --input ../data/n1_results_g20.json \\
                              --sample 500 --compare /tmp/check.out
"""

import argparse
import json
import random
import shutil
import subprocess
import sys
from typing import Any


GAP_HEADER = """\
# Auto-generated by gap_cross_check.py
LoadPackage("numericalsgps");
PrintResult := function(idx, S)
    local m, gens, e, F, c, g, t, L, W, cond;
    m := MultiplicityOfNumericalSemigroup(S);
    gens := MinimalGeneratingSystem(S);
    e := Length(gens);
    F := FrobeniusNumberOfNumericalSemigroup(S);
    cond := F + 1;
    g := Length(GapsOfNumericalSemigroup(S));
    t := Length(PseudoFrobeniusOfNumericalSemigroup(S));
    L := Length(Filtered([0..F], x -> BelongsToNumericalSemigroup(x, S)));
    W := e * L - cond;
    Print("{");
    Print("\\"idx\\":", idx, ",");
    Print("\\"m\\":", m, ",");
    Print("\\"e\\":", e, ",");
    Print("\\"F\\":", F, ",");
    Print("\\"c\\":", cond, ",");
    Print("\\"g\\":", g, ",");
    Print("\\"t\\":", t, ",");
    Print("\\"L\\":", L, ",");
    Print("\\"W\\":", W);
    Print("}\\n");
end;;
"""


def write_gap_script(records: list[dict], path: str) -> int:
    """Write a GAP script that constructs each semigroup from its generators
    and prints the recomputed invariants."""
    with open(path, "w") as f:
        f.write(GAP_HEADER)
        n = 0
        for i, rec in enumerate(records):
            gens = rec.get("generators")
            if not gens:
                continue
            gens_gap = "[" + ",".join(str(x) for x in gens) + "]"
            f.write(f"PrintResult({i}, NumericalSemigroup({gens_gap}));\n")
            n += 1
    return n


def parse_gap_output(path: str) -> dict[int, dict]:
    out = {}
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line.startswith("{"):
                continue
            try:
                obj = json.loads(line)
                out[obj["idx"]] = obj
            except Exception:
                continue
    return out


def compare(records: list[dict], gap_results: dict[int, dict]) -> None:
    mismatches = 0
    checked = 0
    fields = [
        ("m", "multiplicity"),
        ("e", "embedding_dimension"),
        ("F", "frobenius"),
        ("c", "conductor"),
        ("g", "genus"),
        ("t", "type"),
        ("L", "left_elements"),
        ("W", "wilf_number"),
    ]
    for idx, gap_obj in gap_results.items():
        if idx >= len(records):
            continue
        ours = records[idx]
        checked += 1
        diffs = []
        for gk, lk in fields:
            if lk in ours and gap_obj.get(gk) != ours[lk]:
                diffs.append(f"{gk}: gap={gap_obj[gk]} ours={ours[lk]}")
        if diffs:
            mismatches += 1
            print(f"[{idx}] gens={ours.get('generators')}: " + ", ".join(diffs))
    print(f"\nChecked {checked} semigroups, {mismatches} mismatch(es).")


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--input", required=True)
    p.add_argument("--sample", type=int, default=200)
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--gap-script", type=str, default="/tmp/ns_check.g")
    p.add_argument("--compare", type=str, default=None,
                   help="Path to GAP output file (if already run)")
    p.add_argument("--run", action="store_true",
                   help="Attempt to run the GAP script automatically")
    args = p.parse_args()

    with open(args.input) as f:
        data = json.load(f)
    if isinstance(data, dict):
        data = data.get("records") or data.get("semigroups") or []

    rng = random.Random(args.seed)
    if args.sample < len(data):
        indices = sorted(rng.sample(range(len(data)), args.sample))
        sampled = [data[i] for i in indices]
        # Reindex to match GAP output idx field
        records = sampled
    else:
        records = data

    if args.compare:
        gap_results = parse_gap_output(args.compare)
        print(f"Parsed {len(gap_results)} GAP records from {args.compare}.")
        compare(records, gap_results)
        return

    n_written = write_gap_script(records, args.gap_script)
    print(f"Wrote GAP script: {args.gap_script} ({n_written} semigroups).")

    if args.run:
        gap_bin = shutil.which("gap")
        if not gap_bin:
            print("gap binary not found in PATH; run manually:")
            print(f"  gap -q {args.gap_script} > /tmp/ns_check.out")
            sys.exit(2)
        out_path = args.gap_script.replace(".g", ".out")
        print(f"Running: {gap_bin} -q {args.gap_script} > {out_path}")
        with open(out_path, "w") as outf:
            subprocess.run([gap_bin, "-q", args.gap_script], stdout=outf, check=True)
        gap_results = parse_gap_output(out_path)
        compare(records, gap_results)
    else:
        print("Next step: run GAP manually and re-invoke with --compare <output>.")
        print(f"  gap -q {args.gap_script} > /tmp/ns_check.out")
        print(f"  python gap_cross_check.py --input {args.input} "
              f"--sample {args.sample} --seed {args.seed} --compare /tmp/ns_check.out")


if __name__ == "__main__":
    main()
