"""
Build a catalogue of *sharp witnesses* for the unified conjecture

    W_min(m, d) = (m - d) * L(d) - 2 m ,   L(d) = ceil((sqrt(8 d + 1) - 1)/2) + 2.

Input: the JSON files produced by kunz_fast.py in ../results/.
Each file exposes, per defect d, one tuple k = (k_1, ..., k_{m-1}) that
attains W_min(m, d) during the enumeration (the "argmin_k").

For every (m, d) whose observed W_min equals W_pred(m, d) we emit a witness
record containing:

  * the Kunz tuple k,
  * the Apery set   w_i = k_i * m + i  (i = 1..m-1),
  * a minimal generating set of S,
  * the Frobenius number F, conductor c, genus g, type t,
  * L, e, d, W.

The output is written to ../results/sharp_witnesses.json and a short
human-readable digest is printed to stdout.

This script is pure-Python, deterministic, and does not re-enumerate anything:
it only post-processes the per-defect argmin already stored in the JSONs. One
witness per (m, d) is sufficient to prove the predicted bound is *attained*,
which is the mathematical claim the unified conjecture needs.
"""

from __future__ import annotations

import glob
import json
import math
import os
from typing import Iterable

HERE = os.path.dirname(os.path.abspath(__file__))
RESULTS = os.path.normpath(os.path.join(HERE, "..", "results"))


def L_of_d(d: int) -> int:
    if d == 0:
        return 2
    p = math.ceil((math.sqrt(8 * d + 1) - 1) / 2)
    return p + 2


def W_pred(m: int, d: int) -> int:
    return (m - d) * L_of_d(d) - 2 * m


def apery_from_k(k: list[int], m: int) -> list[int]:
    """Apery set Ap(S, m) = {w_1, ..., w_{m-1}} with w_i = k_i * m + i."""
    return [k[i - 1] * m + i for i in range(1, m)]


def semigroup_elements_up_to(apery: list[int], m: int, bound: int) -> set[int]:
    """All n in S with n <= bound, computed from Ap(S, m).

    n in S iff n = 0 or n >= w_{n mod m} (classical characterization).
    """
    S = {0}
    for n in range(1, bound + 1):
        r = n % m
        if r == 0:
            S.add(n)
        else:
            if n >= apery[r - 1]:
                S.add(n)
    return S


def frobenius_conductor(apery: list[int], m: int) -> tuple[int, int]:
    F = max(apery) - m
    return F, F + 1


def genus(apery: list[int], m: int) -> int:
    """g = |N \\ S| = sum_{i=1}^{m-1} floor(w_i / m)  =  sum k_i.

    (Because the gaps in residue class i are i, i+m, ..., w_i - m, giving k_i
    gaps; residue 0 has no gaps.)"""
    return sum((w // m) for w in apery)


def minimal_generators(apery: list[int], m: int) -> list[int]:
    """Return the (sorted) minimal generating set of S.

    S is generated by {m} ∪ Ap(S, m) minus any Apery element that is the sum
    of two non-zero elements of S. We only need sums that stay <= max(apery).
    """
    F = max(apery)
    S_upto = semigroup_elements_up_to(apery, m, F)
    positives = sorted(x for x in S_upto if 0 < x <= F)

    gens: list[int] = [m]
    for w in sorted(apery):
        decomposable = False
        for a in positives:
            if a >= w:
                break
            b = w - a
            if b > 0 and b in S_upto:
                decomposable = True
                break
        if not decomposable:
            gens.append(w)
    return sorted(gens)


def semigroup_type(apery: list[int], m: int) -> int:
    """|PF(S)| where PF(S) = {x in Z \\ S : x + s in S for all s in S, s>0}.

    Classical fact: t(S) = |{i : w_i - m is a pseudo-Frobenius number}|; we
    compute it directly via the definition restricted to Apery (Froberg-
    Gottlieb-Haggkvist): x in PF(S) iff x + w_i in S for all i, where x ranges
    over the "maximal" elements of Ap(S,m) under the partial order
    a <= b  :iff  b - a in S.
    """
    # Partial order on Apery elements.
    S_upto = semigroup_elements_up_to(apery, m, 2 * max(apery))
    maxs: list[int] = []
    for w in apery:
        is_max = True
        for v in apery:
            if v == w:
                continue
            if (v - w) in S_upto and v != w:
                is_max = False
                break
        if is_max:
            maxs.append(w - m)  # PF element
    return len(maxs)


def extract_sharp(results_files: Iterable[str]) -> list[dict]:
    witnesses: list[dict] = []
    for path in sorted(results_files):
        with open(path) as f:
            data = json.load(f)
        m = data["m"]
        K_max = data["K_max"]
        for d_str, rec in data["per_defect"].items():
            d = int(d_str)
            W_obs = rec["W_min"]
            Wp = W_pred(m, d)
            if W_obs != Wp:
                continue  # not sharp at this m
            k = rec["argmin_k"]
            # Trim to length m-1 (C backend pads to MAX_M_C entries).
            k = list(k[: m - 1])
            ap = apery_from_k(k, m)
            F, c = frobenius_conductor(ap, m)
            gens = minimal_generators(ap, m)
            e = len(gens)
            g = genus(ap, m)
            L = (c - d) // max(1, (m - d))  # sanity; recomputed below
            # L from definition L = |S ∩ [0, c-1]| = c - g.
            L = c - g
            t = semigroup_type(ap, m)
            W = e * L - c
            assert W == W_obs, (W, W_obs, m, d)
            assert e == m - d, (e, m - d, k)
            witnesses.append(
                {
                    "m": m,
                    "d": d,
                    "e": e,
                    "L": L,
                    "F": F,
                    "c": c,
                    "g": g,
                    "t": t,
                    "W": W,
                    "W_pred": Wp,
                    "k": k,
                    "apery": ap,
                    "generators": gens,
                    "source": os.path.basename(path),
                    "K_max": K_max,
                }
            )
    return witnesses


def main() -> None:
    files = glob.glob(os.path.join(RESULTS, "m*k*.json"))
    if not files:
        raise SystemExit(f"no results found under {RESULTS}")

    witnesses = extract_sharp(files)

    out_path = os.path.join(RESULTS, "sharp_witnesses.json")
    with open(out_path, "w") as f:
        json.dump({"count": len(witnesses), "witnesses": witnesses}, f, indent=1)

    # Digest.
    print(f"extracted {len(witnesses)} sharp witnesses from {len(files)} files")
    print(f"  -> {out_path}")
    print()
    print(f"{'m':>3} {'d':>3} {'e':>3} {'L':>3} {'W':>4} {'F':>4} {'g':>4} "
          f"{'t':>3}  generators")
    print("-" * 72)
    for w in witnesses:
        gens = ",".join(str(x) for x in w["generators"])
        if len(gens) > 40:
            gens = gens[:37] + "..."
        print(f"{w['m']:>3} {w['d']:>3} {w['e']:>3} {w['L']:>3} "
              f"{w['W']:>4} {w['F']:>4} {w['g']:>4} {w['t']:>3}  <{gens}>")


if __name__ == "__main__":
    main()
